# MedPromptCLIP: Text-Only Prompt Learning for Zero-Shot Cross-Modal Disease Classification
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 256
  TEST:
    BATCH_SIZE: 128
  NUM_WORKERS: 8

INPUT:
  SIZE: (224,224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.5042229,0.50427837,0.5045664]
  PIXEL_STD: [0.22627175,0.22626996,0.22635411]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "adamw"
  LR: 0.005
  MAX_EPOCH: 72
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 3
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-4
  WEIGHT_DECAY: 0.1
  ADAM_BETA1: 0.9
  ADAM_BETA2: 0.98


TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-L/14_PMC"
TRAINER:
  MEDPROMPTCLIP:
    N_CTX_TEXT: 6
    CTX_INIT: "a X-ray image of "
    PREC: "fp16"
    PROMPT_DEPTH_TEXT: 9
    GPT_PATH: "templates/Chest_Xray.json" # templates/pets_prompts_full.json
    USE_TEMPLATES: False
    USE_ATTRIBUTE_DATA: False
    EYE_DOMAIN: True
TEST:
  COMPUTE_CMAT: True