# MedPromptCLIP: Text-Only Prompt Learning for Zero-Shot Cross-Modal Disease Classification
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 256
  TEST:
    BATCH_SIZE: 128
  NUM_WORKERS: 8

INPUT:
  SIZE: (224,224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.40869185,0.26170721,0.14354068]
  PIXEL_STD: [0.26276545,0.17682548,0.10356012]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "adamw"
  LR: 0.03
  MAX_EPOCH: 64
  LR_SCHEDULER: "cosine"
  WEIGHT_DECAY: 0.05
  ADAM_BETA1: 0.9
  ADAM_BETA2: 0.98


TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-L/14_PMC"
TRAINER:
  MEDPROMPTCLIP:
    N_CTX_TEXT: 6
    CTX_INIT: "a fundus image of"
    PREC: "fp16"
    PROMPT_DEPTH_TEXT: 9
    GPT_PATH: "templates/ODIR.json" # templates/pets_prompts_full.json
    USE_TEMPLATES: False
    USE_ATTRIBUTE_DATA: False
    EYE_DOMAIN: False
TEST:
  COMPUTE_CMAT: True    