# MedPromptCLIP: Text-Only Prompt Learning for Zero-Shot Cross-Modal Disease Classification
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 256
  TEST:
    BATCH_SIZE: 128
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.50944512,0.50944512,0.50944512]
  PIXEL_STD: [0.23144044,0.23144044,0.23144044]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

MODEL:
  BACKBONE:
    NAME: "ViT-L/14_PMC"

TRAINER:
  MEDPROMPTCLIP:
    CTX_INIT: "a X-ray image of"
    PREC: "fp16"
TEST:
  COMPUTE_CMAT: True

