# MedPromptCLIP: Text-Only Prompt Learning for Zero-Shot Cross-Modal Disease Classification
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 128
  TEST:
    BATCH_SIZE: 64
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.74060887,0.53310455,0.70590561]
  PIXEL_STD: [0.1279016,0.16060114,0.11905577]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

MODEL:
  BACKBONE:
    NAME: "ViT-L/14_PMC"

TRAINER:
  MEDPROMPTCLIP:
    CTX_INIT: "a pathology image of"
    PREC: "fp16"
TEST:
  COMPUTE_CMAT: True

