# MedPromptCLIP: Text-Only Prompt Learning for Zero-Shot Cross-Modal Disease Classification
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 256
  TEST:
    BATCH_SIZE: 128
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.29985818,0.29984083,0.29985702]
  PIXEL_STD: [0.22477652,0.22477765,0.22477514]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  MEDPROMPTCLIP:
    CTX_INIT: "a CT image of "
    PREC: "fp16"
TEST:
  COMPUTE_CMAT: True

