# Independent Vision Language Prompting
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 2
  TEST:
    BATCH_SIZE: 2
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.40923419,0.28918428,0.20130023]
  PIXEL_STD: [0.31434369,0.22403507,0.17685541]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "adamw"
  LR: 5e-6
  MAX_EPOCH: 40
  LR_SCHEDULER: "cosine"
  WEIGHT_DECAY: 0.15
  ADAM_BETA1: 0.9
  ADAM_BETA2: 0.98

TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-L/14_PMC"

TRAINER:
  IVLP:
    N_CTX_VISION: 4
    N_CTX_TEXT: 6
    CTX_INIT: "an Endoscopy image of "
    PREC: "fp16"
    PROMPT_DEPTH_VISION: 9
    PROMPT_DEPTH_TEXT: 9
TEST:
  COMPUTE_CMAT: True